### ISSUE TITLE
涛哥~

### ISSUE THREAD

**Issue by smilexiamo** [jiangTaoQuite/jiangTaoQuite.github.io#1]
涛哥威武啊~~搞到3点多都不睡觉

**Comment by jiangTaoQuite** [comment]
然而并没有什么卵用

2015-06-25



jiangtao103cp



发件人：xiamo <notifications@github.com>
发送时间：2015-06-24 09:42
主题：[jiangTaoQuite.github.io] 涛哥~ (#1)
收件人："jiangTaoQuite/jiangTaoQuite.github.io"<jiangTaoQuite.github.io@noreply.github.com>
抄送：

涛哥威武啊~~搞到3点多都不睡觉

**Comment by smilexiamo** [comment]
傻逼，issue都不关
